Update SystemInfoHelper.cs
Corona-Studio/ProjBobcat pull request #68
Opened 2022-07-14 23:48 UTC by ABCDCreeper

优化了Java搜索

2022-07-15 04:35 UTC, CodingEric requested changes
We can't merge this PR before the problems being addressed.

2022-07-15 04:35 UTC, CodingEric commented on ProjBobcat/ProjBobcat/Class/Helper/SystemInfoHelper.cs
> +        var DiskName = getDisk();
The code style here should be consistent with other parts of the projects.

2022-07-15 04:35 UTC, CodingEric commented on ProjBobcat/ProjBobcat/Class/Helper/SystemInfoHelper.cs
> +            catch { }
Unnecessary trying & catching, you had better replace it with logical judgements which are more explicit.

2022-07-15 04:35 UTC, CodingEric commented on ProjBobcat/ProjBobcat/Class/Helper/SystemInfoHelper.cs
> +    public static List<string> getDisk()
Repeated and inefficient implementation. Please refer to DeepJavaSearcher.cs .

2022-07-15 04:35 UTC, CodingEric commented on ProjBobcat/Example/Program.cs
> +            foreach (var disk in Disk)
Unnecessary.

2022-07-15 07:31 UTC, CodingEric commented on ProjBobcat/ProjBobcat/Class/Helper/SystemInfoHelper.cs
> +using System.Management;
Note that .NET Core does not support System.Management

2022-07-16 02:05 UTC, ABCDCreeper commented
Fixed

2022-07-16 02:52 UTC, closed without merging